/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2013-03-11 02:40:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Base.*;
import java.util.*;

public final class AbmUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function rellenar(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar indice = document.modificacion.clientes.selectedIndex;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar valor = document.modificacion.clientes[indice].value; \r\n");
      out.write("\tvalor=valor.replace(/[^a-zA-Z 0-9.]+/g,' ');\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.modificacion.nuevoValor.value=valor.toString();\r\n");
      out.write("\t\r\n");
      out.write("}</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function comprobarContrasenia(){\r\n");
      out.write("\tvar contra1=document.alta.contrasenia.value;\r\n");
      out.write("\tvar contra2=document.alta.confirmecontrasenia.value;\r\n");
      out.write("\tif(contra1==contra2 && contra1.lenght > 0 && contra2.lenght > 0){\r\n");
      out.write("\t\talert(\"Contraseñas confirmadas\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else if(contra1 != contra2){\r\n");
      out.write("\t\talert(\"Las contraseñas no coinciden, ingreselas de nuevo\");\r\n");
      out.write("\t\tdocument.alta.contrasenia.value=\"\";\r\n");
      out.write("\t\tdocument.alta.confirmecontrasenia.value=\"\";\r\n");
      out.write("\t\tdocument.alta.contrasenia.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else if(contra1 == \"\" || contra2 == \"\"){\r\n");
      out.write("\t\talert(\"La contraseña no debe quedar vacía, por favor, complétela.\");\r\n");
      out.write("\t\tif(contra1 == \"\")document.alta.contrasenia.focus();\r\n");
      out.write("\t\tif(contra2 == \"\")document.alta.confirmecontrasenia.focus();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("//Validar que el campo de formulario contenga sólo números\r\n");
      out.write("function validacionNumerica(campo_a_validar)  {\r\n");
      out.write("if (isNaN(campo_a_validar.value)) {\r\n");
      out.write("alert(\"Error:\\nEl campo Dni/Legajo, debe tener sólo números.\");\r\n");
      out.write("campo_a_validar.focus();\r\n");
      out.write("return false;\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function comprobarCampos(){\r\n");
      out.write("\t\r\n");
      out.write("\tif(document.alta.nombre.value == \"\"){\r\n");
      out.write("\t\talert(\"Complete el Nombre.\");\r\n");
      out.write("\t\tdocument.alta.nombre.focus();\r\n");
      out.write("\t\treturn false;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.apellido.value == \"\"){\r\n");
      out.write("\t\talert(\"Complete el Apellido.\");\r\n");
      out.write("\t\tdocument.alta.apellido.focus();\r\n");
      out.write("\t\treturn false;\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.usuario.value == \"\"){\r\n");
      out.write("\t\talert(\"Complete el Usuario.\");\r\n");
      out.write("\t\tdocument.alta.usuario.focus();\r\n");
      out.write("\t\treturn false;\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.direccion.value == \"\"){\r\n");
      out.write("\t\talert(\"Complete la Direccion.\");\r\n");
      out.write("\t\tdocument.alta.direccion.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.telefono.value == \"\"){\r\n");
      out.write("\t\talert(\"Complete el Teléfono.\");\r\n");
      out.write("\t\tdocument.alta.telefono.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.dni.value == \"\"){\r\n");
      out.write("\t\talert(\"Complete el Dni.\");\r\n");
      out.write("\t\tdocument.alta.dni.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.legajo.value == \"\"){\r\n");
      out.write("\t\talert(\"Complete el Legajo.\");\r\n");
      out.write("\t\tdocument.alta.legajo.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.contrasenia.value == \"\"){\r\n");
      out.write("\t\talert(\"Complete la Contraseña.\");\r\n");
      out.write("\t\tdocument.alta.contrasenia.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.confirmecontrasenia.value == \"\"){\r\n");
      out.write("\t\talert(\"Por favor, confirme contraseña.\");\r\n");
      out.write("\t\tdocument.alta.confirmecontrasenia.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.dni.value == \"\"){\r\n");
      out.write("\t\talert(\"Por favor, complete Dni.\");\r\n");
      out.write("\t\tdocument.alta.dni.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.alta.legajo.value == \"\"){\r\n");
      out.write("\t\talert(\"Por favor, complete legajo.\");\r\n");
      out.write("\t\tdocument.alta.legajo.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tif(comprobarContrasenia()== false){\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function usuarioDuplicado(usuario){\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Abm de Usuarios</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style/style.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#E6E6E6\">\r\n");
      out.write("<a>Bienvenido al Alta,Baja,Modificación de Usuarios.</a><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

session.setAttribute("solicitaAbm", "AbmUsuario");//ÉSTE SETEO ESTARÁ EN TODOS LOS JSP DE ABM PARA INDICAR AL ABMCOMMITER LA ACCION CORRESPONDIENTE


String accion=request.getParameter("accion");//ÉSTE ACCION VIENE CARGADO DE MENUABM CON (Alta,Baja o Modificación)
session.setAttribute("accion", accion);//ACA ACCION PASA A SER UN ATRIBUTO DE SESION PARA SER LLEVADO AL ABMCOMMITER

out.println("Que hago? :"+ accion);



//request.getParameter("abm"); es el que hay que usar para saber accion a tomar


metodosSql metodos=new metodosSql();
ArrayList<String>categoriaPersonal;
categoriaPersonal=metodos.consultarUnaColumna("Select descripcion from proyectoweb.categoriaPersonal ");

if(accion.equals("Alta"))
{ out.println("Eligió dar de alta un nuevo usuario, complete los campos. ");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form  name=\"alta\" action=\"AbmCommitter.jsp\" method=\"post\" onsubmit= \" return comprobarCampos()\" >\r\n");
      out.write("<input type=\"hidden\" name=\"contraseniaOK\" value=\"false\">\r\n");
      out.write("\t\t<table border=\"3\" >\r\n");
      out.write("\t\t <thead>\r\n");
      out.write("\t\t </thead>\r\n");
      out.write("         <tbody> \r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Nombre</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"nombre\"  /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Apellido</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"apellido\"  /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Usuario</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"usuario\"  /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Contraseña</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"contrasenia\"  /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Confirme Contraseña</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"confirmecontrasenia\"  /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Permiso</td>\r\n");
      out.write("\t\t\t\t<td><select name=\"permiso\">\r\n");
      out.write("\t\t\t<option value=\"administrador\">Administrador</option>\t\t\t\r\n");
      out.write("\t\t\t<option value=\"usuario\">Usuario</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Dni</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"dni\"  onblur=\"validacionNumerica(dni)\"/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Legajo</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"legajo\" onblur=\"validacionNumerica(legajo)\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Dirección</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"direccion\"  /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>teléfono</td>\r\n");
      out.write("\t\t\t\t<td><input name=\"telefono\"  /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Categoría</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select name=\"categoria\"  >\r\n");
      out.write("\t        ");

			for (int i = 0; i < categoriaPersonal.size(); i++)

				out.println(" <option value=" + java.net.URLEncoder.encode(categoriaPersonal.get(i), "UTF-8") + ">"
						+ categoriaPersonal.get(i) + "</option>");
			
      out.write("\r\n");
      out.write("\t\t\t</select></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Confirme</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" value=\"Crear Usuario\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("         </tbody> \r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\t\r\n");
 
}
else if(accion.equals("Baja"))
{

	
      out.write("<form name=\"baja\" action=\"AbmCommitter.jsp\" method=\"post\">");

	out.println("Eligio dar de baja un usuario, seleccione de la lista desplegable.<br><br>");


 

metodosSql metodos2=new metodosSql();
ArrayList<String>usuarios=metodos2.consultarUnaColumna("SELECT usuario FROM proyectoweb.userlogin where Inhabilitado='NO' order by usuario");
out.println("Usuarios");

out.println(" <select name=" + " usuarios " + ">");

for (int i = 0; i < usuarios.size(); i++)
	//encodeURIComponent(unencoded) para javascript
	//java.net.URLEncoder.encode(usuarios.get(i), "UTF-8")
	out.println(" <option value=" + java.net.URLEncoder.encode(usuarios.get(i), "UTF-8") + ">"
			+ usuarios.get(i) + "</option>");

out.println("</select>");
out.println("<br>");



      out.write("<input type=\"submit\" value=\"Borrar!\"></input>\r\n");
      out.write("\r\n");
      out.write("</form>");

}
else if(accion.equals("Modificacion"))
{

	
      out.write("<form name=\"modificacion\" action=\"AbmCommitter.jsp\" method=\"post\">");

	out.println("Eligio modificar un cliente, seleccione de la lista desplegable.<br><br>");

metodosSql metodos3=new metodosSql();
ArrayList<String>clientes=metodos3.consultarUnaColumna("select descripcion from cliente where Inhabilitado='NO' order by descripcion");
out.println("Clientes");

out.println(" <select name=" + " clientes " + "onChange='rellenar()'>");

for (int i = 0; i < clientes.size(); i++)
	//encodeURIComponent(unencoded) para javascript
	//java.net.URLEncoder.encode(usuarios.get(i), "UTF-8")
	out.println(" <option value=" + java.net.URLEncoder.encode(clientes.get(i), "UTF-8") + ">"
			+ clientes.get(i) + "</option>");

out.println("</select>");
out.println("<br>");





      out.write("\r\n");
      out.write("<a>Ingrese aquí el nuevo nombre del cliente</a>\r\n");
      out.write("<br><input name=\"nuevoValor\" value=\"\" size=\"40\">\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"submit\" value=\"Modificar\"></input>\r\n");
      out.write("\r\n");
      out.write("</form>");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<a href=\"MenuABM.jsp\" >Volver a ABM</a><br>\r\n");
      out.write("<a href=\"MenuPpal.jsp\" >Volver a menu principal</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
