/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2013-01-09 02:24:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import Excel.*;
import java.util.ArrayList;
import Base.*;

public final class Descarga_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

try
{
	//opciones disponibles
	//matrizNoFiltrada
	//matrizFiltrada
	
	/**Preguntar, viene con filtro la consulta?
			
			si si{
				es administrador?{
				consulta con filtro administrador
				}si no{
				consulta con filtro usuario
				}
		   }si no{
				es administrador?{
				consulta sin filtro para administrador
			
			}sino{
				consulta sin filtro para usuario
		}
	}
	*
	*
	*
	*/
	
	String filtrar=session.getAttribute("filtrar").toString();
	String nivelAcceso=session.getAttribute("permiso").toString();
	String rutaAlArchivo=null;	
    ArrayList<ArrayList<String>>matrix=null;
   
    
	metodosSql metodos=new metodosSql();
    //String nFile = "BUSTAMANTE.xls";	
    if(filtrar.equals("si")){
    	
    	if(nivelAcceso.equals("administrador")){
    		matrix=metodos.consultar(session.getAttribute("consultaAdministradorFiltro").toString());
    	}else{
    		matrix=metodos.consultar(session.getAttribute("consultaUsuarioFiltro").toString());
    	}
    	
    }else{
    	
		if(nivelAcceso.equals("administrador")){
			
			matrix=metodos.consultar(session.getAttribute("consultaAdministrador").toString());
    		
    	}else{
    		matrix=metodos.consultar(session.getAttribute("consultaUsuario").toString());
    		
    	}
    	
    }
    
   
    
    
    
    	
    EscrituraExcel esc=new EscrituraExcel();
    //cabecera matriz NRO REGISTRO TAREA SUBTAREA DESCRIPCION DEPARTAMENTO USUARIO CLIENTE HS TIPO HS FECHA ESTADO 
    ArrayList<String>cabecera=new ArrayList<String>();
    cabecera.add("NRO REGISTRO");
    cabecera.add("TAREA");
    cabecera.add("SUBTAREA");
    cabecera.add("DESCRIPCION");
    cabecera.add("DEPARTAMENTO");
    cabecera.add("USUARIO");
    cabecera.add("CLIENTE");
    cabecera.add("HS");
    cabecera.add("TIPO HS");
    cabecera.add("FECHA");
    cabecera.add("ESTADO");
    matrix.add(0, cabecera);
    
    
    FileInputStream archivo = new FileInputStream(rutaAlArchivo=esc.crearExcelDesdeMatriz(matrix,"C:\\DescargasPWEB\\", session.getAttribute("usuario").toString()));//"C:/"+nFile); 
    int longitud = archivo.available();
    byte[] datos = new byte[longitud];
    archivo.read(datos);
    archivo.close();
    
    response.setContentType("application/vnd.ms-excel");
    response.setHeader("Content-Disposition","attachment;filename="+rutaAlArchivo);//nFile);   
   
    
    ServletOutputStream ouputStream = response.getOutputStream();
    ouputStream.write(datos);
    ouputStream.flush();
    ouputStream.close();
 
    	
  
    	

   
 
    
   
    
    
    	
}
catch(IllegalStateException il){
	System.out.println(il.getMessage());
	
}
catch(IOException io){
	System.out.println(io.getMessage());
	
}
catch(Exception e)
{ 
	System.out.println(e.getMessage());
}


	



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
