/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2012-08-04 03:32:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Base.metodosSql;
import java.util.*;

public final class CargaDiaria_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>CARGA DIARIA DE DATOS</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");
out.println("<body bgcolor=\"#F2EFFB\">"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"Hacerupdate.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
String usuario=session.getAttribute("usuario").toString(); 
      out.write('\r');
      out.write('\n');
String permiso=session.getAttribute("esAdministrador").toString();
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");

		
		out.println("Bienvenido "+usuario+"<br>");
			//Comienza la creacion del select Especialidad
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		
		metodosSql metodos=new metodosSql();
		out.println("El dia de HOY usted tiene "+ metodos.consultarUnaColumna("SELECT sum(horastrabajadas) FROM proyectoweb.registrogral "+
				" where fecha='"+metodos.dameFechaDeHoy()+"' and "+ 
				" dnipersonal=(select dni from proyectoweb.userlogin "+
				" where usuario='"+usuario+"') ;").get(0)+" horas trabajadas<br>");
		
		/*if(request.getParameter("user").equals("leo")){
			
			
		}else{
			
			response.sendRedirect("invaliduser.html");
			
		}*/
		/*out.println("Especialidad");
		
			
			ArrayList<String> array =new ArrayList<String>();
			
			array=metodos.consultarUnaColumna("SELECT especialidad FROM personal");
			array.add(0,"");
			
			out.println(" <select name=" + " especialidad " + ">");

			for (int i = 0; i < array.size(); i++)

				out.println(" <option value=" + array.get(i) + ">"
						+ array.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");*/

			//---------------------------------fin del select especialidad---------------------------------------------------------------------------------
			//---------------------------------comienza  select nombre---------------------------------------------------------------------------------
			
			/*ArrayList<String> array1 = new ArrayList<String>();
			("SELECT Apellido,Nombre FROM personal order by Apellido");
			

			out.println(" <select name=" + " nombre " + ">");

			for (int i = 0; i < array1.size(); i++)

				out.println(" <option value=" + array1.get(i) + ">"
						+ array1.get(i) + "</option>");

			out.println("</select>");*/

			//----------------------------------fin del select nombre----------------------------------------------------------------------------------------  

			//---------------------------------comienza  select cliente---------------------------------------------------------------------------------
			out.println("Aquí puede modificar la fecha si lo desea, o bien use la fecha de hoy por defecto <br>");
			out.println("<input type= text name=" + " Fecha " +" value= "+metodos.dameFechaDeHoy()+"> mantenga el formato AAAA-MM-DD<br>");
			
			
			
			out.println("Cliente.....");
			ArrayList<String> array2 = new ArrayList<String>();
			
			array2=metodos.consultarUnaColumna("SELECT descripcion from cliente");
			array2.add(0,"");
			

			out.println(" <select name=" + " cliente " + ">");

			for (int i = 0; i < array2.size(); i++)

				out.println(" <option value=" + array2.get(i) + ">"
						+ array2.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");
			//----------------------------------fin del select cliente----------------------------------------------------------------------------------------  

			//---------------------------------comienza  select dia---------------------------------------------------------------------------------
		/*	out.println("Dia");
			ArrayList<String> array3 = new ArrayList<String>();
			
			array3=metodos.consultarUnaColumna("SELECT dia from dia");
			array3.add(0,"");
			

			out.println(" <select name=" + " dia " + ">");

			for (int i = 0; i < array3.size(); i++)

				out.println(" <option value=" + array3.get(i) + ">"
						+ array3.get(i) + "</option>");

			out.println("</select>");
			
			out.println("<br>");*/

			//----------------------------------fin del select dia----------------------------------------------------------------------------------------  

			//---------------------------------comienza  select mes---------------------------------------------------------------------------------
			/*out.println("Mes");
			ArrayList<String> array4 = new ArrayList<String>();
			
			array4=metodos.consultarUnaColumna("SELECT nombre from mes ");
			array4.add(0,"");
			
			out.println(" <select name=" + " mes " + ">");

			for (int i = 0; i < array4.size(); i++)

				out.println(" <option value=" + array4.get(i) + ">"
						+ array4.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");*/

			//---------------------------------comienza  select tipo de hora---------------------------------------------------------------------------------
			out.println("Tipo de hora");
			ArrayList<String> array5 = new ArrayList<String>();
			
			array5=metodos.consultarUnaColumna("SELECT descripcion from tipoHora ");
			array5.add(0,"");

			out.println(" <select name=" + " tipohora " + ">");

			for (int i = 0; i < array5.size(); i++)

				out.println(" <option value=" + array5.get(i) + ">"
						+ array5.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");

			//---------------------------------comienza  select tipo de Departamento---------------------------------------------------------------------------------
			out.println("Depto.......");
			ArrayList<String> array6 = new ArrayList<String>();
			
			array6=metodos.consultarUnaColumna("SELECT descripcion from departamento ");
			array6.add(0,"");
			
			out.println(" <select name=" + " departamento " + ">");

			for (int i = 0; i < array6.size(); i++)

				out.println(" <option value=" + array6.get(i) + ">"
						+ array6.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");

			//---------------------------------comienza  select tipo de Tarea---------------------------------------------------------------------------------
			out.println("Tarea.......");
			ArrayList<String> array7 = new ArrayList<String>();
			
			array7=metodos.consultarUnaColumna("SELECT descripcion from tarea ");
			array7.add(0,"");
			

			out.println(" <select name=" + " tarea " + ">");

			for (int i = 0; i < array7.size(); i++)

				out.println(" <option value=" + array7.get(i) + ">"
						+ array7.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");
			
			//---------------------------------comienza  select tipo de SubTarea---------------------------------------------------------------------------------
			out.println("Subtarea....");
			ArrayList<String> array8 = new ArrayList<String>();
			
			array8=metodos.consultarUnaColumna("SELECT descripcion from subtarea ");
			array8.add(0,"");
			

			out.println(" <select name=" + " subtarea " + ">");

			for (int i = 0; i < array8.size(); i++)

				out.println(" <option value=" + array8.get(i) + ">"
						+ array8.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");
			out.println("<br>");
			
			//------------------------------------------------------------------------
			out.println("<br>Hs utilizadas");

			out.println(" <select name=" + " horas " + ">");

			for (double i = 0; i < 23;i = i + 0.5 )
			
			out.println(" <option value=" + i + ">"	+ i + "</option>");

			out.println("</select>");
			out.println("<br><br><br><br><br><br>");
			
			//--------------------dato adicional--------------------------------------
			
			out.println("<br>Dato adicional:<br>"+
					"<textarea name=comentarios rows=2 cols=50></textarea>"+ 
					"<br>");
			
			
			
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Aceptar\" />\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
