/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2012-08-23 05:20:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Base.metodosSql;
import java.util.ArrayList;

public final class Tabla_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Tabla maestra</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#E6E6E6\"><br>\r\n");

if(session.getAttribute("usuario")==null){
		response.sendRedirect("index.jsp");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <a href=\"MenuPpal.jsp\">Volver al Menú</a><br>\r\n");
      out.write("\r\n");
String filtrar=session.getAttribute("filtrar").toString(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>NRO REGISTRO</th>\r\n");
      out.write("<th>TAREA</th>\r\n");
      out.write("<th>SUBTAREA</th>\r\n");
      out.write("<th>DESCRIPCION</th>\r\n");
      out.write("<th>DEPARTAMENTO</th>\r\n");
      out.write("<th>USUARIO</th>\r\n");
      out.write("<th>CLIENTE</th>\r\n");
      out.write("<th>HS</th>\r\n");
      out.write("<th>TIPO HS</th>\r\n");
      out.write("<th>FECHA</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("<tbody>\r\n");


String hsTotal;
metodosSql metodos=new metodosSql();
if(filtrar.equals("no")){
//pide atributos de session de menuPpal


ArrayList<ArrayList<String>> matriz=new ArrayList<ArrayList<String>>();

String usuario=session.getAttribute("usuario").toString();

String dniUser=metodos.consultarUnaColumna("select dni from userlogin where usuario ='"+ session.getAttribute("usuario").toString()+"'").get(0);

ArrayList<ArrayList<String>> matrizPers=new ArrayList<ArrayList<String>>();

matrizPers=metodos.consultar("SELECT apellido,nombre,especialidad FROM proyectoweb.personal where dni ="+dniUser);

String nivelAcceso=session.getAttribute("esAdministrador").toString();

String tipoUsuario;

if(nivelAcceso.equals("false")){//si es usuario
	tipoUsuario="Usuario";
	String datosPersonales=matrizPers.get(0).get(0)+" "+matrizPers.get(0).get(1)+" "+matrizPers.get(0).get(2);
	out.println("Consulta para el usuario  : "+dniUser+" "+datosPersonales);
}else{
	tipoUsuario="Administrador";
}


out.println("<br> Usted es "+tipoUsuario+" del sistema");

///sin filtro

if(tipoUsuario.equals("Usuario")){
matriz=metodos.consultar("SELECT idregistrogral,tarea,subtarea,descripcion,departamento,dnipersonal,cliente,horastrabajadas,tipohora,fecha,estado"+
		" FROM proyectoweb.REGISTROGRAL"+
		" where dniPersonal= (select dni from proyectoweb.userlogin where usuario='"+usuario+"')");

		
}else{
	matriz=metodos.consultar("SELECT idregistrogral,tarea,subtarea,descripcion,departamento,"+
			"usuario,cliente,horastrabajadas,tipohora,fecha,estado "+
			" FROM proyectoweb.registrogral r,proyectoweb.userlogin u "+
			"where u.dni= r.dnipersonal order by usuario;" );
	
	
	
}

for(int i=0;i<matriz.size();i++){
	out.println("<tr>");
	for(int j=0;j<11;j++){//10 son la cantidad de elementos del ancho
		out.println("<td>"+matriz.get(i).get(j)+"</td>");
		
	}
	out.println("<tr>");
}


if(tipoUsuario.equals("Usuario")){
	hsTotal=metodos.consultarUnaColumna("SELECT SUM(horastrabajadas) FROM REGISTROGRAL where dniPersonal="+dniUser).get(0);
}else{
	hsTotal=metodos.consultarUnaColumna("SELECT SUM(horastrabajadas) FROM REGISTROGRAL r,userlogin u where u.dni= r.dnipersonal").get(0);
}
}


//////////////////////////////CONN FILTRO//////////////////////////////////////////////////////



else{// Si la opcion en el request, viene con filtrado.
	//--------------------------------------------------------------------------------------------------------------------------------------------------------
	//session.setAttribute("filtrar", "no");
	String desde=request.getParameter("Desde");
	String hasta=request.getParameter("Hasta");
	String filtro=request.getParameter("Filtro");
	String criterio=request.getParameter("Criterio");
	String paramFiltro;
	
	 hsTotal="sin horas";
	out.println("Usted consultó desde "+desde+" hasta  "+hasta+" "+" filtró por "+filtro+" usando el critrio de filtro "+criterio+ ". <br><br>");
	
	ArrayList<ArrayList<String>> matriz2=new ArrayList<ArrayList<String>>();
	ArrayList<ArrayList<String>> matrizPers2=new ArrayList<ArrayList<String>>();
	
	String dniUser=metodos.consultarUnaColumna("select dni from userlogin where usuario ='"+ session.getAttribute("usuario").toString()+"'").get(0);

	
	matrizPers2=metodos.consultar("SELECT apellido,nombre,especialidad FROM proyectoweb.personal where dni ="+dniUser);

	String nivelAcceso=session.getAttribute("esAdministrador").toString();
	
	String tipoUsuario;
	
	if(nivelAcceso.equals("false")){//si no es administrador
		tipoUsuario="Usuario";
		String datosPersonales=matrizPers2.get(0).get(0)+" "+matrizPers2.get(0).get(1)+" "+matrizPers2.get(0).get(2);
		out.println("Consulta para el usuario  : "+dniUser+" "+datosPersonales);
	}else{
		tipoUsuario="Administrador";
	}


	out.println("<br> Usted es "+tipoUsuario+" del sistema");
	
	//llenando la matriz con los filtros//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	if(tipoUsuario.equals("Usuario")){//solo mostrara los registros donde aparezca su dni
//	
	matriz2=metodos.consultar("Select idregistrogral,tarea,subtarea,descripcion,departamento,usuario,cliente,horastrabajadas,tipohora,fecha"+
			" from proyectoweb.registrogral r,proyectoweb.personal p,proyectoweb.userlogin u "+
			" where "+filtro+"='"+criterio+"' and "+
			" fecha >='"+desde+"' and "+
			" fecha <='"+hasta+"'and "+
			" r.dnipersonal= p.dni and "+
			"p.dni= "+dniUser+" and "+
			"u.dni= "+dniUser);
	
	}else{//si es administrador vera todos los registros no importa el usuario
		matriz2=metodos.consultar("Select idregistrogral,tarea,subtarea,descripcion,departamento,usuario,cliente,horastrabajadas,tipohora,fecha"+
	" from proyectoweb.registrogral r,proyectoweb.personal p,proyectoweb.userlogin u "+
				" where "+filtro+"='"+criterio+"' and "+
				" fecha >='"+desde+"' and "+
				" fecha <='"+hasta+"'and "+
				" r.dnipersonal=p.dni and "+
				"u.dni=p.dni");//duda con esta....
	}
	
	
	
//MOSTRANDO POR PANTALLA///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	for(int i=0;i<matriz2.size();i++){
		out.println("<tr>");
		for(int j=0;j<10;j++){//8 son la cantidad de elementos del ancho
			out.println("<td>"+matriz2.get(i).get(j)+"</td>");
			
		}
		out.println("<tr>");
	}
//FIN MOSTRANDO POR PANTALLA/////////////////////////////////////////////////////////////////////////////////////////////////////////////





//horas sumadas para la consulta de arriba si es usuario

	if(tipoUsuario.equals("Usuario")){
		hsTotal=metodos.consultarUnaColumna("SELECT SUM(horastrabajadas)"+
				" from proyectoweb.registrogral r,proyectoweb.personal p "+
				" where "+filtro+"='"+criterio+"' and "+
				" fecha >='"+desde+"' and "+
				" fecha <='"+hasta+"'and "+
				" r.dnipersonal= p.dni and "+
				"p.dni= "+dniUser).get(0);
	}
	
	
	
	
	
	else{
		hsTotal=metodos.consultarUnaColumna("SELECT SUM(horastrabajadas)"+
	" from proyectoweb.registrogral r,proyectoweb.personal p,proyectoweb.userlogin u "+
				"  where "+filtro+"='"+criterio+"' and "+
						" fecha >='"+desde+"' and "+
						" fecha <='"+hasta+"'and "+
						" r.dnipersonal=p.dni and "+
						"u.dni=p.dni").get(0);
	}
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("El total de horas para esta consulta es de ");
      out.print(hsTotal );
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<a href=\"MenuPpal.jsp\">Volver a menú</a><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
