/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2013-03-11 02:46:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;
import Abm.*;
import Base.*;

public final class AbmCommitter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Committer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#819FF7\">\r\n");

ConexionMySql conexion=new ConexionMySql();

AdministradorABM admin=new AdministradorABM();

if(session.getAttribute("solicitaAbm").equals("AbmCliente")){//inicio si viene de abmcliente
	//out.println("vino de AbmCliente");
	
	if(session.getAttribute("accion").equals("Alta")){//inicio si es para alta cliente
		
		Cliente cli=new Cliente(Integer.parseInt(request.getParameter("numeroCliente")),request.getParameter("razonSocial").toString());
		if(admin.darDeAlta(cli, "proyectoweb", "cliente")==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos cargados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

		}		
		
		else{
			
			
      out.write("<script type=\"text/javascript\">alert(\"Hubo un problema, intente de nuevo por favor.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");\r\n");
      out.write("\t\t\t</script>");
		
			
		}
		
		
	}//fin si es para alta cliente
	
	
	
	
	
	//si viene de baja hacer..
	if(session.getAttribute("accion").equals("Baja")){//inicio si es para baja cliente
		int statusBajaCliente=0;
		AdministradorABM adminBaja=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		out.println("baja");
		
		String cliente=URLDecoder.decode(request.getParameter("clientes"), "UTF-8");
		
		
		
		
		String sentencia="Select idCliente from cliente where descripcion='"+cliente+"' and inHabilitado='NO';";
		int idCliente=Integer.parseInt(metodos.consultarUnaColumna(sentencia).get(0));
		Cliente clienteDelete=new Cliente(idCliente,cliente);
		statusBajaCliente= adminBaja.InHabilitar(clienteDelete,conexion.getBase(),"cliente");
		if(statusBajaCliente==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos borrados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se borraron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
		
		
		
	}//fin si es para baja cliente	
	
	if(session.getAttribute("accion").equals("Modificacion")){//inicio si es para modificacion cliente
		out.println("modificacion");
	try{
		int statusModifCliente=0;
		AdministradorABM adminModif=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		
		
		
		String cliente=URLDecoder.decode(request.getParameter("clientes"), "UTF-8");
		
		
		
		
		
		int idCliente=Integer.parseInt(metodos.consultarUnaColumna("SELECT max(idCliente) FROM proyectoweb.cliente;").get(0));
		idCliente++;
		int idClienteDel=Integer.parseInt(metodos.consultarUnaColumna("SELECT idCliente FROM proyectoweb.cliente where descripcion= '"+cliente+"' and inHabilitado='NO';").get(0));
		String nuevaDescripcionCliente=request.getParameter("nuevoValor");
		Cliente nuevoCli=new Cliente(idCliente,nuevaDescripcionCliente);
		Cliente clienteDelete=new Cliente(idClienteDel,cliente);
		
		statusModifCliente= adminModif.InHabilitar(clienteDelete,conexion.getBase(),"cliente");
		statusModifCliente=statusModifCliente+adminModif.darDeAlta(nuevoCli,conexion.getBase(), "cliente");
		
		if(statusModifCliente==2){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos modificados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se modificaron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
	}catch(Exception e){
		out.println("Error, compruebe los datos suministrados e intente de nuevo... :\n "+e.getMessage());
		
		
      out.write("<a href=\"MenuABM.jsp\" >Volver a ABM</a>");

		
	}
	
	
	
	
	
	
		
	}//fin si es para modificacion de cliente
	
	
	
	
	
	
}//fin si viene de abmcliente
else if(session.getAttribute("solicitaAbm").equals("AbmTarea")){//inicio si viene de AbmTarea
	//out.println("vino de AbmTarea");
	
	if(session.getAttribute("accion").equals("Alta")){//inicio si es para alta tarea
		
		Tarea tar=new Tarea(Integer.parseInt(request.getParameter("numeroTarea")),request.getParameter("tarea").toString().toUpperCase());
		//usando upper case por primera vez en el proyecto
		if(admin.darDeAlta(tar, "proyectoweb", "tarea")==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos cargados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

		}		
		
		else{
			
			
      out.write("<script type=\"text/javascript\">alert(\"Hubo un problema, intente de nuevo por favor.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");\r\n");
      out.write("\t\t\t</script>");
		
			
		}
		
		
	}//fin si es para alta cliente
	
	
	
	
	
	//si viene de baja hacer..
	if(session.getAttribute("accion").equals("Baja")){//inicio si es para baja cliente
		int statusBajaCliente=0;
		AdministradorABM adminBaja=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		out.println("baja");
		
		String tarea=URLDecoder.decode(request.getParameter("tareas"), "UTF-8");
		
		
		
		
		String sentencia="Select idTarea from tarea where descripcion='"+tarea+"' and inHabilitado='NO';";
		int idTarea=Integer.parseInt(metodos.consultarUnaColumna(sentencia).get(0));
		Tarea tareaDelete=new Tarea(idTarea, tarea);
		
		statusBajaCliente= adminBaja.InHabilitar(tareaDelete,conexion.getBase(),"tarea");
		if(statusBajaCliente==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos borrados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se borraron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
		
		
		
	}//fin si es para baja tarea	
	
	if(session.getAttribute("accion").equals("Modificacion")){//inicio si es para modificacion tarea
		out.println("modificacion");
	try{
		int statusModifTarea=0;
		AdministradorABM adminModif=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		
		
		
		String tarea=URLDecoder.decode(request.getParameter("tareas"), "UTF-8");
		
		
		
		
		
		int idTarea=Integer.parseInt(metodos.consultarUnaColumna("SELECT max(idTarea) FROM proyectoweb.tarea;").get(0));
		idTarea++;
		int idTareaDel=Integer.parseInt(metodos.consultarUnaColumna("SELECT idTarea FROM proyectoweb.tarea where descripcion= '"+tarea+"' and inHabilitado='NO';").get(0));
		String nuevaDescripcionTarea=request.getParameter("nuevoValor");
		Tarea nuevaTarea=new Tarea(idTarea,nuevaDescripcionTarea);
		Tarea tareaDelete=new Tarea(idTareaDel,tarea);
		
		statusModifTarea= adminModif.InHabilitar(tareaDelete,conexion.getBase(),"tarea");
		statusModifTarea=statusModifTarea+adminModif.darDeAlta(nuevaTarea,conexion.getBase(), "tarea");
		statusModifTarea=statusModifTarea+adminModif.reasignarSubtareas(tareaDelete, nuevaTarea);
		
		if(statusModifTarea==3){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos modificados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se modificaron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
	}catch(Exception e){
		out.println("Error, compruebe los datos suministrados e intente de nuevo... :\n "+e.getMessage());
		
		
      out.write("<a href=\"MenuABM.jsp\" >Volver a ABM</a>");

		
	}
	
	
	
	
	
	
		
	}//fin si es para modificacion de tarea
	
	
	
	
	
	
}//fin si viene de abmtarea

else if(session.getAttribute("solicitaAbm").equals("AbmSubTarea")){//inicio si viene de AbmSubTarea
	//out.println("vino de AbmSubTarea");
	
	if(session.getAttribute("accion").equals("Alta")){//inicio si es para alta Subtarea
		metodosSql metodos=new metodosSql();
		
		String nombreTareaPadre=request.getParameter("tareas").toString();
		String idTarPadre=metodos.consultarUnaColumna("SELECT idTarea FROM proyectoweb.tarea where descripcion='"+nombreTareaPadre+"';").get(0);
		int idTareaPadre=Integer.parseInt(idTarPadre);
	
		Subtarea subTar=new Subtarea(Integer.parseInt(request.getParameter("numeroSubTarea")),idTareaPadre,  request.getParameter("subTarea").toString().toUpperCase());
		//usando upper case por primera vez en el proyecto
		if(admin.darDeAlta(subTar, "proyectoweb", "subtarea")==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos cargados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

		}		
		
		else{
			
			
      out.write("<script type=\"text/javascript\">alert(\"Hubo un problema, intente de nuevo por favor.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");\r\n");
      out.write("\t\t\t</script>");
		
			
		}
		
		
	}//fin si es para alta tarea
	
	
	
	
	
	//si viene de baja hacer..
	if(session.getAttribute("accion").equals("Baja")){//inicio si es para baja subtarea
		int statusBajaSubtarea=0;
		AdministradorABM adminBaja=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		out.println("baja");
		
		String subTarea=URLDecoder.decode(request.getParameter("subtareas"), "UTF-8");
		
		
		
		
		String sentencia="Select idsubTarea from subtarea where descripcion='"+subTarea+"' and inHabilitado='NO';";
		int idSubTarea=Integer.parseInt(metodos.consultarUnaColumna(sentencia).get(0));
		Subtarea subTareaDelete=new Subtarea(idSubTarea, subTarea);
		
		statusBajaSubtarea= adminBaja.InHabilitar(subTareaDelete,conexion.getBase(),"subtarea");
		if(statusBajaSubtarea==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos borrados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se borraron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
		
		
		
	}//fin si es para baja subtarea	
	
	if(session.getAttribute("accion").equals("Modificacion")){//inicio si es para modificacion de subtarea
		out.println("modificacion");
	try{
		//´+´+
		int statusModifSubTarea=0;
		AdministradorABM adminModif=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		
		
		
		String subTarea=URLDecoder.decode(request.getParameter("subTareas"), "UTF-8");
		
		
		
		
		
		int idSubTarea=Integer.parseInt(metodos.consultarUnaColumna("SELECT max(idsubTarea) FROM proyectoweb.subtarea;").get(0));
		idSubTarea++;
		int idSubTareaDel=Integer.parseInt(metodos.consultarUnaColumna("SELECT idSubTarea FROM proyectoweb.subtarea where descripcion= '"+subTarea+"' and inHabilitado='NO';").get(0));
		int idtareaPadre=Integer.parseInt(metodos.consultarUnaColumna("SELECT tareaPadre FROM proyectoweb.subtarea where idSubTarea= '"+idSubTareaDel+"' ;").get(0));
		String nuevaDescripcionTarea=request.getParameter("nuevoValor");
		Subtarea nuevaSubTarea=new Subtarea(idSubTarea,nuevaDescripcionTarea);
		Subtarea subTareaDelete=new Subtarea(idSubTareaDel,subTarea);
		subTareaDelete.setTareaPadre(idtareaPadre);
		nuevaSubTarea.setTareaPadre(subTareaDelete.getTareaPadre());
		
		statusModifSubTarea= adminModif.InHabilitar(subTareaDelete,conexion.getBase(),"subtarea");
		statusModifSubTarea=statusModifSubTarea+adminModif.darDeAlta(nuevaSubTarea,conexion.getBase(), "subtarea");
		statusModifSubTarea=statusModifSubTarea+adminModif.InHabilitar(subTareaDelete, conexion.getBase(), "subtarea");
		
		if(statusModifSubTarea==3){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos modificados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se modificaron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
	}catch(Exception e){
		out.println("Error, compruebe los datos suministrados e intente de nuevo... :\n "+e.getMessage());
		
		
      out.write("<a href=\"MenuABM.jsp\" >Volver a ABM</a>");

		
	}
	
	
	
	
	
	
		
	}//fin si es para modificacion de subtarea
	
	
	
	
	
	
}//fin si viene de abmSubtarea

else if(session.getAttribute("solicitaAbm").equals("AbmDepto")){//inicio si viene de AbmDepartamento
	//out.println("vino de AbmDepartamento");
	
	if(session.getAttribute("accion").equals("Alta")){//inicio si es para alta Departamento
		
		Departamento _depto=new Departamento(Integer.parseInt(request.getParameter("numerodepartamento")),request.getParameter("departamento").toString().toUpperCase());
		//usando upper case por primera vez en el proyecto
		if(admin.darDeAlta(_depto, "proyectoweb", "Departamento")==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos cargados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

		}		
		
		else{
			
			
      out.write("<script type=\"text/javascript\">alert(\"Hubo un problema, intente de nuevo por favor.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");\r\n");
      out.write("\t\t\t</script>");
		
			
		}
		
		
	}//fin si es para alta Departamento
	
	
	
	
	
	//si viene de baja hacer..
	if(session.getAttribute("accion").equals("Baja")){//inicio si es para baja Departamento
		int statusBajaCliente=0;
		AdministradorABM adminBaja=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		out.println("baja");
		
		String Departamento=URLDecoder.decode(request.getParameter("departamentos"), "UTF-8");
		
		
		
		
		String sentencia="Select idDepartamento from Departamento where descripcion='"+Departamento+"' and inHabilitado='NO';";
		int idDepartamento=Integer.parseInt(metodos.consultarUnaColumna(sentencia).get(0));
		Departamento DepartamentoDelete=new Departamento(idDepartamento, Departamento);
		
		statusBajaCliente= adminBaja.InHabilitar(DepartamentoDelete,conexion.getBase(),"Departamento");
		if(statusBajaCliente==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos borrados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se borraron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
		
		
		
	}//fin si es para baja Departamento	
	
	if(session.getAttribute("accion").equals("Modificacion")){//inicio si es para modificacion Departamento
		out.println("modificacion");
	try{
		int statusModifDepartamento=0;
		AdministradorABM adminModif=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		
		
		
		String Departamento=URLDecoder.decode(request.getParameter("departamentos"), "UTF-8");
		
		
		
		
		
		int idDepartamento=Integer.parseInt(metodos.consultarUnaColumna("SELECT max(idDepartamento) FROM proyectoweb.Departamento;").get(0));
		idDepartamento++;
		int idDepartamentoDel=Integer.parseInt(metodos.consultarUnaColumna("SELECT idDepartamento FROM proyectoweb.Departamento where descripcion= '"+Departamento+"' and inHabilitado='NO';").get(0));
		String nuevaDescripcionDepartamento=request.getParameter("nuevoValor");
		Departamento nuevaDepartamento=new Departamento(idDepartamento,nuevaDescripcionDepartamento);
		Departamento DepartamentoDelete=new Departamento(idDepartamentoDel,Departamento);
		
		statusModifDepartamento= adminModif.InHabilitar(DepartamentoDelete,conexion.getBase(),"Departamento");
		statusModifDepartamento=statusModifDepartamento+adminModif.darDeAlta(nuevaDepartamento,conexion.getBase(), "Departamento");
		
		
		if(statusModifDepartamento==2){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos modificados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se modificaron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
	}catch(Exception e){
		out.println("Error, compruebe los datos suministrados e intente de nuevo... :\n "+e.getMessage());
		
		
      out.write("<a href=\"MenuABM.jsp\" >Volver a ABM</a>");

		
	}
	
	
	
	
	
	
		
	}//fin si es para modificacion de Departamento
	
	
	
	
	
	
}//fin si viene de abmDepartamento

else if(session.getAttribute("solicitaAbm").equals("AbmUsuario")){//inicio si viene de AbmUsuario
	//out.println("vino de AbmUsuario");
	try{
	if(session.getAttribute("accion").equals("Alta")){//inicio si es para alta Usuario
		
		String usuario=request.getParameter("usuario");
		String contrasenia=request.getParameter("contrasenia");
		String nombre=request.getParameter("nombre");
		String apellido=request.getParameter("apellido");
		String permiso=request.getParameter("permiso");
		int dni=Integer.parseInt(request.getParameter("dni"));
		int legajo=Integer.parseInt(request.getParameter("legajo"));
		String direccion=request.getParameter("direccion");
		String telefono=request.getParameter("telefono");
		metodosSql metodos=new metodosSql();
		int categoria=metodos.dameNroCategoria(request.getParameter("categoria"));
		
		
		Usuario _Usuario=new Usuario(usuario,contrasenia,permiso,dni,legajo,apellido,nombre,direccion,telefono,categoria);
		//usando upper case por primera vez en el proyecto
		if(admin.darDeAltaUsuario(_Usuario)==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos cargados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

		}		
		
		else{
			
			
      out.write("<script type=\"text/javascript\">alert(\"Hubo un problema, intente de nuevo cambiando el nombre de usuario por favor, puede que ya exista ese usuario y que esté deshabilitado.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");\r\n");
      out.write("\t\t\t</script>");
		
			
		}
		
		
	}//fin si es para alta Usuario
	}catch(Exception e){
		out.println("Error!!! intente de nuevo si persiste el problema copie el error y envíelo a su administrador."+e.getMessage());
	}
	
	
	
	
	
	//si viene de baja hacer..
	if(session.getAttribute("accion").equals("Baja")){//inicio si es para baja Usuario
		int statusBajaUsuario=0;
		AdministradorABM adminBaja=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		out.println("baja");
		
		String usuario=URLDecoder.decode(request.getParameter("usuarios"), "UTF-8");
		
		
		
		
		
		
		Usuario UsuarioDelete=new Usuario(usuario,null,null,0,0,null,null,null,null,0);
		
		statusBajaUsuario= adminBaja.InHabilitar(UsuarioDelete,conexion.getBase(),"userlogin");
		if(statusBajaUsuario==1){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos borrados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se borraron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
		
		
		
	}//fin si es para baja Usuario	
	/*
	if(session.getAttribute("accion").equals("Modificacion")){//inicio si es para modificacion Usuario
		out.println("modificacion");
	try{
		int statusModifUsuario=0;
		AdministradorABM adminModif=new AdministradorABM();
		metodosSql metodos=new metodosSql();
		
		
		
		String Usuario=URLDecoder.decode(request.getParameter("Usuarios"), "UTF-8");
		
		
		
		
		
		int idUsuario=Integer.parseInt(metodos.consultarUnaColumna("SELECT max(idUsuario) FROM proyectoweb.Usuario;").get(0));
		idUsuario++;
		int idUsuarioDel=Integer.parseInt(metodos.consultarUnaColumna("SELECT idUsuario FROM proyectoweb.Usuario where descripcion= '"+Usuario+"' and inHabilitado='NO';").get(0));
		String nuevaDescripcionUsuario=request.getParameter("nuevoValor");
		Usuario nuevaUsuario=new Usuario(idUsuario,nuevaDescripcionUsuario);
		Usuario UsuarioDelete=new Usuario(idUsuarioDel,Usuario);
		
		statusModifUsuario= adminModif.InHabilitar(UsuarioDelete,conexion.getBase(),"Usuario");
		statusModifUsuario=statusModifUsuario+adminModif.darDeAlta(nuevaUsuario,conexion.getBase(), "Usuario");
		
		
		if(statusModifUsuario==2){
			
      out.write("<script type=\"text/javascript\">alert(\"Datos modificados con éxito!\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}else{
			
      out.write("<script type=\"text/javascript\">alert(\"Los datos no se modificaron, intente de nuevo...\");\r\n");
      out.write("\t\t\t document.location=(\"MenuABM.jsp\");//redireccion \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</script>");

			
		}
	}catch(Exception e){
		out.println("Error, compruebe los datos suministrados e intente de nuevo... :\n "+e.getMessage());
		
		
      out.write("<a href=\"MenuABM.jsp\" >Volver a ABM</a>");

		
	}
	
	
	
	
	
	
		
	}//fin si es para modificacion de Usuario
	*/
	
	
	
	
	
}//fin si viene de abmUsuario





      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
