/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2013-02-03 23:42:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Base.metodosSql;
import java.util.*;

public final class CargaDiaria_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<script> \r\n");
      out.write("    function DameCampoFecha(fech){ \r\n");
      out.write("    \tvar form_element = document.getElementById('fech');\r\n");
      out.write("    \treturn form_element;\r\n");
      out.write("    } \r\n");
      out.write("   </script> \r\n");
      out.write("   \r\n");
      out.write(" <SCRIPT>\r\n");
      out.write(" function compruebaExcesoDeHoras(hs,maxHs){\r\n");
      out.write("\t if(hs>=maxhs){\r\n");
      out.write("\t\t if(confirm('ha excedido el límite de '+maxhs+' confirma?')){\r\n");
      out.write("\t\t\t alert('Confirmó');\r\n");
      out.write("\t\t }else{\r\n");
      out.write("\t\t\t alert('No confirmó');\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t }\r\n");
      out.write("\t \r\n");
      out.write(" }\r\n");
      out.write(" </SCRIPT>\r\n");
      out.write(" \r\n");
      out.write("  <SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT>\r\n");
      out.write("\r\n");
      out.write("function Damehs(hs,fecha) { \r\n");
      out.write("\tif(hs==null){\r\n");
      out.write("\t\t alert(\"Ud tiene if 0 horas trabajadas en \"+fecha);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"Ud tiene else \"+hs+\" horas trabajadas en \"+fecha);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("<script> \r\n");
      out.write("    function irAconsultaHS(){ \r\n");
      out.write("    \tresponse.sendRedirect(\"consultaHsTrabajadas.jsp\");\r\n");
      out.write("    } \r\n");
      out.write("   </script> \r\n");
      out.write("<script>\r\n");
      out.write("function Envia(destino){\r\n");
      out.write("\tCargaDiaria.action=destino;\r\n");
      out.write("\tCargaDiaria.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>CARGA DIARIA DE DATOS</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");




/*session.setAttribute("permiso","administrador");
session.setAttribute("usuario","leandro");
session.setAttribute("fechaCarga","2012-11-10");*/






HttpSession sesion=request.getSession();
if(sesion.equals(null)){
	response.sendRedirect("index.jsp");
}



out.println("<body bgcolor=\"#F2EFFB\">"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form name=\"CargaDiaria\" action=\"Hacerupdate.jsp\" method=\"post\">\r\n");
      out.write("\r\n");


String usuario=session.getAttribute("usuario").toString(); 
String permiso=session.getAttribute("permiso").toString();
String fechaCarga=session.getAttribute("fechaCarga").toString();//toma la fecha del menu, la de hoy por defecto.




		
		
		out.println("Bienvenido "+usuario+"<br>");
			//Comienza la creacion del select Especialidad
		
		
		metodosSql metodos=new metodosSql();
		
		
      out.write("\r\n");
      out.write("\t\t<div align=\"right\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<a>Ingrese aqui su consulta</a><br>\r\n");
      out.write("\t\t<a>Use el formato AAAA-MM-DD</a><br>\r\n");
      out.write("\t\t<input type=\"text\" id=\"fech\" name=fechaConsulta ><br>\r\n");
      out.write("\t\t<input type=\"button\"  value=\"Check\"  OnClick=\"Envia('consultaHsTrabajadas.jsp')\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

		
		
			String horasDeHoy="0";
			if (metodos.consultarUnaColumna("SELECT sum(horastrabajadas) FROM proyectoweb.registrogral "+
					" where fecha='"+fechaCarga+"' and "+ 
					" dnipersonal=(select dni from proyectoweb.userlogin "+
					" where usuario='"+usuario+"') ;").get(0)==null){
				horasDeHoy="0";
				
			}else{
				horasDeHoy=metodos.consultarUnaColumna("SELECT sum(horastrabajadas) FROM proyectoweb.registrogral "+
						" where fecha='"+fechaCarga+"' and "+ 
						" dnipersonal=(select dni from proyectoweb.userlogin "+
						" where usuario='"+usuario+"') ;").get(0);
			}
			
		out.println("En el dia "+fechaCarga+" usted tiene "+horasDeHoy+" horas trabajadas<br><br>");
		
		

			//----------------------------------fin del select nombre----------------------------------------------------------------------------------------  

			//---------------------------------comienza  select cliente---------------------------------------------------------------------------------
			
			
			out.println("Aquí puede modificar la fecha si lo desea, o bien use la fecha de hoy por defecto <br>");
			out.println("<input type= text name=" + " Fecha " +" value= "+fechaCarga+"> mantenga el formato AAAA-MM-DD<br>");
			
			
			
			out.println("Cliente.....");
			ArrayList<String> array2 = new ArrayList<String>();
			
			array2=metodos.consultarUnaColumna("SELECT descripcion from cliente");
			array2.add(0,"");
			

			out.println(" <select name=" + " cliente " + " >");

			for (int i = 0; i < array2.size(); i++)

				out.println(" <option value=" + java.net.URLEncoder.encode(array2.get(i), "UTF-8") + ">"
						+ array2.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");
			

			//---------------------------------comienza  select tipo de hora---------------------------------------------------------------------------------
			out.println("Tipo de hora");
			ArrayList<String> array5 = new ArrayList<String>();
			
			array5=metodos.consultarUnaColumna("SELECT descripcion from tipoHora ");
			array5.add(0,"");

			out.println(" <select name=" + " tipohora " + ">");

			for (int i = 0; i < array5.size(); i++)

				out.println(" <option value=" + array5.get(i) + ">"
						+ array5.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");

			//---------------------------------comienza  select tipo de Departamento---------------------------------------------------------------------------------
			out.println("Depto.......");
			ArrayList<String> array6 = new ArrayList<String>();
			
			array6=metodos.consultarUnaColumna("SELECT descripcion from departamento ");
			array6.add(0,"");
			
			out.println(" <select name=" + " departamento " + ">");

			for (int i = 0; i < array6.size(); i++)

				out.println(" <option value=" + java.net.URLEncoder.encode(array6.get(i), "UTF-8") + ">"
						+ array6.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");

			//---------------------------------comienza  select tipo de Tarea---------------------------------------------------------------------------------
			out.println("Tarea.......");
			ArrayList<String> array7 = new ArrayList<String>();
			
			array7=metodos.consultarUnaColumna("SELECT descripcion from tarea ");
			array7.add(0,"");
			

			out.println(" <select name=" + " tarea " + ">");

			for (int i = 0; i < array7.size(); i++)

				out.println(" <option value=" + java.net.URLEncoder.encode(array7.get(i), "UTF-8") + ">"
						+ array7.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");
			
			//---------------------------------comienza  select tipo de SubTarea---------------------------------------------------------------------------------
			out.println("Subtarea....");
			ArrayList<String> array8 = new ArrayList<String>();
			
			array8=metodos.consultarUnaColumna("SELECT descripcion from subtarea ");
			array8.add(0,"");
			

			out.println(" <select name=" + " subtarea " + ">");

			for (int i = 0; i < array8.size(); i++)

				out.println(" <option value=" + java.net.URLEncoder.encode(array8.get(i), "UTF-8") + ">"
						+ array8.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");
			out.println("<br>");
			
			//------------------------------------------------------------------------
			out.println("<br>Hs utilizadas");

			out.println(" <select name=" + " horas " + ">");

			for (double i = 0; i < 23;i = i + 0.5 )
			
			out.println(" <option value=" + i + ">"	+ i + "</option>");

			out.println("</select>");
			out.println("<br><br><br><br><br><br>");
			
			//--------------------dato adicional--------------------------------------
			
			out.println("<br>Dato adicional:<br>"+
					"<textarea name=comentarios rows=2 cols=50></textarea>"+ 
					"<br>");
			
			
			
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Aceptar\"/><br><br>\r\n");
      out.write("\t\t<a href=\"MenuPpal.jsp\" >Volver a menu</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
