/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2012-09-04 05:11:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Base.metodosSql;
import java.util.ArrayList;

public final class CierreGlobal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#E6E6E6\">\r\n");
      out.write("<table border=\"3\">\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("<th>USUARIO</th>\r\n");
      out.write("<th>ENERO</th>\r\n");
      out.write("<th>FEBRERO</th>\r\n");
      out.write("<th>MARZO</th>\r\n");
      out.write("<th>ABRIL</th>\r\n");
      out.write("<th>MAYO</th>\r\n");
      out.write("<th>JUNIO</th>\r\n");
      out.write("<th>JULIO</th>\r\n");
      out.write("<th>AGOSTO</th>\r\n");
      out.write("<th>SEPTIEMBRE</th>\r\n");
      out.write("<th>OCTUBRE</th>\r\n");
      out.write("<th>NOVIEMBRE</th>\r\n");
      out.write("<th>DICIEMBRE</th>\r\n");
      out.write("<th>AÑO</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("<tbody>\r\n");
      out.write("\r\n");

String permisoDeUser = session.getAttribute("permiso").toString();
String user=session.getAttribute("usuario").toString();

ArrayList<ArrayList<String>> matriz2=new ArrayList<ArrayList<String>>();
if(permisoDeUser.equalsIgnoreCase("administrador")){
metodosSql metodos=new metodosSql();
	matriz2=metodos.consultar("select USUARIO,ENERO,FEBRERO,MARZO, ABRIL, MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE,ANIO  from MesesEstado  "+
			"where anio = "+metodos.dameAnio());
}else{
	metodosSql metodos=new metodosSql();
	matriz2=metodos.consultar("select USUARIO,ENERO,FEBRERO,MARZO, ABRIL, MAYO,JUNIO,JULIO,AGOSTO,SEPTIEMBRE,OCTUBRE,NOVIEMBRE,DICIEMBRE,ANIO  from MesesEstado  "+
			"where anio = "+metodos.dameAnio()+" and usuario = '"+user+"'");
	
}
	
	
	
	
//MOSTRANDO POR PANTALLA///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	for(int i=0;i<matriz2.size();i++){
		out.println("<tr>");
		for(int j=0;j<14;j++){//13 son la cantidad de elementos del ancho
			if(matriz2.get(i).get(j)==null){
				out.println("<td> - </td>");
			}else{
			out.println("<td>"+matriz2.get(i).get(j)+"</td>");
			}
			
		}
		out.println("<tr>");
	}

      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<BR>\r\n");
      out.write("<a href=\"MenuPpal.jsp\">Volver al Menú</a><br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
