/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.28
 * Generated at: 2012-09-04 05:12:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import Base.metodosSql;

public final class FiltroConsulta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>FILTRO DE CONTENIDO</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#E6E6E6\">\r\n");
if(session.equals(null)){
		response.sendRedirect("index.jsp");
	}

      out.write("\r\n");
      out.write("\t<input type=\"hidden\" value=\"si\" name=\"filtrar\">\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"EspFiltro.jsp\" method=\"post\">\r\n");
      out.write("\t\t<H1>Aquí puede filtrar el contenido de la tabla de datos</H1>\r\n");
      out.write("\t\t");
      out.print(session.getAttribute("usuario"));
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t");

	
		session.setAttribute("filtrar", "si");
			metodosSql metodos = new metodosSql();
			out.println("Desde");
			ArrayList<String> array = new ArrayList<String>();

			array = metodos	.consultarUnaColumna("SELECT fecha from registrogral where fecha is not null order by fecha asc ");

			out.println("<input type= text name=" + " Desde " +" value= "+metodos.consultarUnaColumna("select min(fecha)from registrogral").get(0)+"><br>");
			
			
			out.println("Hasta ");
			out.println("<input type= text name=" + " Hasta " +" value= "+metodos.consultarUnaColumna("select max(fecha)from registrogral").get(0)+">");
			
						
			
			out.println("<br>");
			out.println("<br>");
			//out.println(request.getParameter("Desde"));

			out.println("Filtrado por");
			ArrayList<String> array2 = new ArrayList<String>();

			array2 = metodos.consultarUnaColumna("SELECT COLUMN_NAME"
					+ " FROM information_schema.COLUMNS"
					+ " WHERE TABLE_SCHEMA  LIKE 'PROYECTOWEB'"
					+ " AND TABLE_NAME = 'REGISTROGRAL' ");

			out.println(" <select name=" + " Filtro " + ">");

			for (int i = 0; i < array2.size(); i++)

				out.println(" <option value=" + array2.get(i) + ">"
						+ array2.get(i) + "</option>");

			out.println("</select>");
			out.println("<br>");
			out.println("<br>");
			
		
      out.write("\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Aceptar\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t   <a href=\"MenuPpal.jsp\">Volver al Menú</a><br><br>\r\n");
      out.write("\t\t\t   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
